from app.schemas.common import APIResponse, ErrorResponse
from app.schemas.user import (
    UserProfileBase,
    UserProfileUpdate,
    UserProfileResponse,
    SubjectBase,
    SubjectCreate,
    SubjectResponse,
    AcademicSummaryResponse,
)
from app.schemas.evidence import (
    EvidenceBase,
    EvidenceResponse,
    ProjectCreate,
    ProjectDetailResponse,
    HackathonCreate,
    HackathonDetailResponse,
    CertificateCreate,
    CertificateDetailResponse,
    EvidenceCreateGeneral,
    SkillLinkInput,
    SkillLinkResponse,
)
from app.schemas.skill import (
    SkillBase,
    SkillCreate,
    SkillResponse,
    SkillDetailResponse,
    ReactFlowNode,
    ReactFlowEdge,
    SkillGraphResponse,
    RoleBase,
    RoleResponse,
    RoleDetailResponse,
    RoleSkillItem,
)
from app.schemas.gap_analysis import GapAnalysisResponse
from app.schemas.mission import MissionGenerateRequest, MissionResponse
from app.schemas.integrations import (
    GitHubStatusResponse,
    GitHubConnectRequest,
    InsightsStatusResponse,
)

__all__ = [
    "APIResponse",
    "ErrorResponse",
    "UserProfileBase",
    "UserProfileUpdate",
    "UserProfileResponse",
    "SubjectBase",
    "SubjectCreate",
    "SubjectResponse",
    "AcademicSummaryResponse",
    "EvidenceBase",
    "EvidenceResponse",
    "ProjectCreate",
    "ProjectDetailResponse",
    "HackathonCreate",
    "HackathonDetailResponse",
    "CertificateCreate",
    "CertificateDetailResponse",
    "EvidenceCreateGeneral",
    "SkillLinkInput",
    "SkillLinkResponse",
    "SkillBase",
    "SkillCreate",
    "SkillResponse",
    "SkillDetailResponse",
    "ReactFlowNode",
    "ReactFlowEdge",
    "SkillGraphResponse",
    "RoleBase",
    "RoleResponse",
    "RoleDetailResponse",
    "RoleSkillItem",
    "GapAnalysisResponse",
    "MissionGenerateRequest",
    "MissionResponse",
    "GitHubStatusResponse",
    "GitHubConnectRequest",
    "InsightsStatusResponse",
]
